---
# file: backup.yml
  - hosts: "{{ target }}"
    remote_user: answerable
    sudo: yes
    roles:
      - { role: 'gcloud', tags: [ 'gcloud' ] }
      - { role: 'mysqldump', tags: [ 'mysqldump'] }
