---
# Initial linode image and create remote user account for ansible.
- hosts: "{{ target }}"
  remote_user: root
  sudo: no
  roles:
    - init

- hosts: localhost
  connection: local
  sudo: yes
  tasks:
    - name: Generate correct locale
      locale_gen:
        name: zh_TW.UTF-8
        state: present

    - name: Create target directory.
      file: path=/etc/ansible/target/{{ target }} state=directory

    - name: Create hostname directory.
      template: src=roles/init/templates/hostname.j2 dest=/etc/ansible/target/{{ target }}/hostname
    - name: Create redirect file.
      template: src=roles/init/templates/redirect.j2 dest=/etc/ansible/target/{{ target }}/redirect
    - name: Create user file.
      template: src=roles/init/templates/user.j2 dest=/etc/ansible/target/{{ target }}/user
    - name: Create vmail file.
      template: src=roles/init/templates/vmail.j2 dest=/etc/ansible/target/{{ target }}/vmail

    - name: Set system hostname
      hostname: name={{ hostname }}
