---
# file: rolling_upgrade.yml
- hosts: "{{ target }}"
  remote_user: answerable
  sudo: yes
  roles:
    - common
    - timezone
    - ntp
    - logrotate
    - {role: gcloud, tags:[start]}
    - {role: mysqldump, tags:[start, all-sites]}
  vars:
    timezone: Asia/Taipei
    ntp_timezone: Asia/Taipei
  tasks:
    - include: roles/common/tasks/update_docker.yml
      when: update_docker
  handlers:
    - include: roles/nginx/handlers/main.yml
